import StreamVideoProvider from '@/Providers/StreamClientProviders'
import { Metadata } from 'next';
import React, { Children, ReactNode } from 'react'

export const metadata: Metadata = {
  icons:{
    icon: '/icons/logo.svg'
  },
  title: "Yoom Meet",
  description: "Generated by create next app",
};

const RootLayout = ({children}: {children: ReactNode}) => {
  return (
    <main>
        <StreamVideoProvider>
        {children}
        </StreamVideoProvider>
        
    </main>
  )
}

export default RootLayout